### ISSUE TITLE
Prevent test from pulling in duplicate answers

### ISSUE THREAD

**Issue by Planet-math** [Asgard-Web-Solutions/aesir-study-center#157]
if you have multiple cards that have the same answer. When a question gets pulled it can pull the multiple answers but they are different like shown below.

![E3F56166-808B-438E-B510-01B4F9919596](https://github.com/jonzenor/interval-flash-cards/assets/54007781/5ae6829e-7a80-44e3-92ff-62c64e8e4b5a)

**Comment by jonzenor** [comment]
Fixed
