### ISSUE TITLE
Multiple choice answers correct even if wrong answer is given

### ISSUE THREAD

**Issue by jonzenor** [Asgard-Web-Solutions/aesir-study-center#64]
If you have a multiple choice test, and all correct choices were selected, but also a wrong choice was given, then the test still gives a 100% for that answer. It should be counted as wrong.

**Comment by Planet-math** [comment]
Should it be a percentage. Like if you get 2/3 you get a 66% for the question and if you answer a wing answer as correct it deducts another point so it would be 33% for the question. Or something like that
